Issue #24
Terasology/PolyWorld pull request #26
Opened 2020-10-02 19:17 UTC by Wdestroier

Hi! I solved the name clash and changed the Region class name to GraphRegion as suggested.

2020-10-02 19:55 UTC, jdrueckert requested changes
Hi @Wdestroier,
thanks for the PR.
I believe you missed a few spots though. For instance, `LevelSpawnSystem` still imports `org.terasology.polyworld.graph.Region` which, expectedly, it cannot find anymore now.
Please adjust these spots as well :slightly_smiling_face:

2020-10-03 00:42 UTC, Wdestroier commented
Hi! @jdrueckert I found the LevelSpawnSystem class in the org.terasology.lost package, am I missing any dependency?

2020-10-03 07:23 UTC, jdrueckert commented
@Wdestroier Yes you're absolutely right, sorry about that, my brain must be a bit gooey already :roll_eyes: 
I just wanted to test you're PR and saw that it doesn't compile. But that's because `Lost` depends on `PolyWorld` and uses the `Region`. So in order to not break the `Lost` gameplay we'd need to adjust it to the change in here.
Are you up for adding another PR and then we can merge both?

2020-10-03 07:26 UTC, jdrueckert approved these changes

2020-10-04 08:57 UTC, jdrueckert commented
So we had another potential contributor ask for taking https://github.com/Terasology/PolyWorld/issues/24 (ping @gaurav9822). I mentioned that they maybe can take on the `Lost` side of this.

2020-10-14 20:28 UTC, skaldarnar approved these changes

2020-10-14 20:28 UTC, skaldarnar commented on src/main/java/org/terasology/polyworld/IslandWorldGenerator.java
> +        CirclePickerClosest<org.terasology.polyworld.graph.GraphRegion> picker = new CirclePickerClosest<>(pos2d);
This should now be possible without the fully qualified name (as there is no name clash anymore)
```suggestion
        CirclePickerClosest<GraphRegion> picker = new CirclePickerClosest<>(pos2d);
```
This change would likely need an import, though.

2020-10-14 20:28 UTC, skaldarnar commented on src/main/java/org/terasology/polyworld/IslandWorldGenerator.java
> +            for (org.terasology.polyworld.graph.GraphRegion r : g.getRegions()) {
```suggestion
            for (GraphRegion r : g.getRegions()) {
```

2020-10-14 20:56 UTC, merged